name: CD AWS Lambds

on:
  push:
    branches:
      - main

jobs:
  deploy-aws-lambda:
    runs-on: ubuntu-latest
    permissions:
      # This is required for requesting GitHub's OIDC Token
      # See https://github.com/aws-actions/configure-aws-credentials
      id-token: write
    env:
      REGION: eu-west-3
      FUNCTION_NAME: joke_lambda
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt
      - uses: axel-op/package-java-aws-lambda@main
        id: package
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ env.REGION }}
      - name: Deploy on AWS
        env:
          JAR: ${{ steps.package.outputs.deployment-file }}
        run: aws lambda update-function-code --function-name $FUNCTION_NAME --zip-file "fileb://$JAR"
