name: CD AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Build with Maven
        run: mvn -B package -DskipTests
      
      - name: Upload Maven Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Joke_lambda_Artifacts
          path: target/joke-api-lambda-1.0-SNAPSHOT.jar
      
          
  deploy_source:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: Joke_lambda_Artifacts 
          
      - name: checkout source code
        uses: actions/checkout@v4
      - name: default deploy
        uses: appleboy/lambda-action@v0.1.9
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: gorush
          zip_file: target/joke-api-lambda-1.0-SNAPSHOT.jar
  
